### PR TITLE
Srsexton94/meetnhire

### PR DESCRIPTION
**Pull request by srsexton94**
Hey y'all! Long time, no scrum :)

I made a bunch of edits (mostly styling/styling-related) to the subidos client just to freshen it up a bit since Meet & Hire is coming up!

Biggest changes:
* made the sidebar collapsable
* broke index view into columns on bigger screens
* adjusted sidebar styling (finally fits to screen proper!)
* added shorten-name helper to keep index view names <18char

That's pretty much it!  Let me know if you have any questions & slack me when you're done in case I don't see your response here?

Hope y'alls post-GA life is going well so far & you're safe and well!

### CODE REVIEW

**Comment by srsexton94** [comment]
Ooh and I almost forgot - I got some feedback from an interview lately that a lack of some sort of loading indicator was a big issue - I just added one for auth events I'll try and get around to one for resource events too

**Comment by srsexton94** [comment]
Hey thanks @ks603!  Good catches (I've been having a bunch of problems with tab icons lately oddly enough - not sure where the react one came from)

But I think both those issues should be fixed now!  and I did get to add in the loaders for resource events too (which I think really helps especially for `post`ing a resource, the API tends to respond pretty slowly...)

**Comment by srsexton94** [comment]
Hey @JakeSeib if this is helpful!
https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository

**Comment by JakeSeib** [comment]
> Hey @JakeSeib if this is helpful!
> https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository

Ah, yeah, that should do it! Don't think I've ever actually had occasion to set multiple remotes before, but makes sense. Thanks!

**Pull request merged**
